### ISSUE TITLE
Using sprintf and passing no parameters causes runtime crash

### ISSUE THREAD

**Issue by DignitySAMP** [oscar-broman/strlib#20]
My code:

`SendAdminMessage(sprintf("[Bug Abusing] (%d) %s has tried to enter a car as a driver whilst in injury, tased or beanbag mode.")) ;`

Result:

`[debug] Server crashed while executing dev.amx
[debug] AMX backtrace:
[debug] #0 native format () in samp03svr
[debug] #1 0004de50 in ?? (15967488, 60159728, 1081487103, 577, 101, 60421768, 449452, 12, 1, 2, ... <22 more arguments>) at D:\Google Drive\SA-MP\2020\.workplace\_@_github\sols\compiler\include\strlib.inc:1697
[debug] #2 00051794 in public OnPlayerStateChange () at D:\Google Drive\SA-MP\2020\.workplace\_@_github\sols\compiler\include\YSI\..\YSI_Visual\..\YSI_Core\y_master\_impl.inc:603`

strlib.inc:1697

`#emit LCTRL       5 <- 1697`

After adding parameters no issues remain.

**Comment by oscar-broman** [comment]
There's not much that can be done about this, since strlib is not responsible for the implementation of `format`.
