### ISSUE TITLE
error 025: function heading differs from prototype

### ISSUE THREAD

**Issue by Gabriel-CSS** [oscar-broman/strlib#22]
_strlib.inc(173) : error 025: function heading differs from prototype_

line 173: `forward strreplace(string[], const search[], const replacement[], bool:ignorecase = false, pos = 0, limit = -1, maxlength = sizeof(string));`

Why could this be happening?

**Comment by oscar-broman** [comment]
You probably have another include that defines strreplace.

Try adding this before you include strlib:
`#define strreplace strlib_strreplace`

**Comment by Gabriel-CSS** [comment]
SOLVED. Thank you so much!
