### ISSUE TITLE
Decoding problems

### ISSUE THREAD

**Issue by Walter-Correa** [oscar-broman/strlib#8]
Hello.
This symbols **Ã©**(letter **é**) is not decoding:
`new dest[15];
utf8decode(dest, "JosÃ©");`

**Expected:** José (UTF8 Decode: http://www.cafewebmaster.com/online_tools/utf_decode)
**But result:** Jos

**Tried:** 
`utf8decode(dest, "JoÃ©s");`
**Expected:** Joés
**But:** Jo/s

**Comment by oscar-broman** [comment]
Make sure the text encoding of your .pwn file is correct. It should work!

**Comment by Walter-Correa** [comment]
**It is not from a pwn file but from a webpage:**
http://api.db-ip.com/v2/free/189.114.201.9/city

**Code:**
```
new string[128],ip[32];
GetPlayerIp(playerid, ip, sizeof(ip));
format(string, sizeof string, "api.db-ip.com/v2/free/%s/city", ip);
HTTP(playerid, HTTP_GET, string, "", "CityResponse");

forward CityResponse(index, response, data[]);
public CityResponse(index, response, data[])
{
	if(response == 200)
	{
		new city[50];
		utf8decode(city, data);
		printf("City: %s",city);
	}
	return 1;
}

Result: São Jos
```

**Comment by oscar-broman** [comment]
Where do you see the output? Server log or chat?

What's your Windows language? Does `São` display correctly? Can you write José in the chat?

**Comment by oscar-broman** [comment]
Could you do this:

```print(ret_ strfrombin(data, strlen(data)))```

**Comment by Walter-Correa** [comment]
**Here are the details:**
The server is running on a **VPS - Windows Server 2008 SP1 - Portuguese**

**Where do you see the output?** Chat

**What's your Windows language?** Portuguese

**Does `São` display correctly?** Yes - http://prntscr.com/k2jdga

**Can you write José in the chat?**Yes - http://prntscr.com/k2jd4f

**print(ret_strfrombin(data, strlen(data))):** 00000053000000C3000000A30000006F000000200000004A0000006F00000073000000C3000000A9

**Thank you!**

**Comment by oscar-broman** [comment]
What happens if you do this:
```
public CityResponse(index, response, data2[])
{
new data[64];
strcat(data, data2);
strcat(data, "XXX");

// rest of the function
```

I.e. append something to the end of it, to see if it's a bug with the last character.

**Comment by oscar-broman** [comment]
Try this file: https://raw.githubusercontent.com/oscar-broman/strlib/3896d093fc5970f4b3ef84970fca1ab53e5d3e38/strlib.inc

**Comment by Walter-Correa** [comment]
**I tried only:**

> Try this file: https://raw.githubusercontent.com/oscar-broman/strlib/3896d093fc5970f4b3ef84970fca1ab53e5d3e38/strlib.inc

**But not solved!**

**So, I tried:**
> https://raw.githubusercontent.com/oscar-broman/strlib/3896d093fc5970f4b3ef84970fca1ab53e5d3e38/strlib.inc

**And**

> public CityResponse(index, response, data2[])
> {
> new data[64];
> strcat(data, data2);
> strcat(data, "XXX");
> 
> // rest of the function

**Result:** http://prntscr.com/k2k5wv

**Comment by oscar-broman** [comment]
Ok, I think it was off by 2 - not 1!

https://raw.githubusercontent.com/oscar-broman/strlib/f1e38a661b5f76b16f74223460bb51be6cbf8744/strlib.inc

**Comment by Walter-Correa** [comment]
Problem solved! Many thanks for this include, for your dedication and helpfulness!

**Comment by oscar-broman** [comment]
Great!
